apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openchoreo-sample-platform
  namespace: flux-system
spec:
  interval: 5m
  path: ./platform
  prune: true
  sourceRef:
    kind: GitRepository
    name: openchoreo-sample-gitops
